/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class whl_bsdiff_BsDiff */

#ifndef _Included_whl_bsdiff_BsDiff
#define _Included_whl_bsdiff_BsDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     whl_bsdiff_BsDiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_whl_bsdiff_BsDiff_diff
        (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
